/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author Chamod
 */
public class Signupform extends javax.swing.JFrame {

    /**
     * Creates new form Signupform
     */
    public Signupform() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        txt_add3 = new javax.swing.JTextField();
        btn_signup = new javax.swing.JButton();
        rbtn_male = new javax.swing.JRadioButton();
        txt_lastname = new javax.swing.JTextField();
        rbtn_female = new javax.swing.JRadioButton();
        txt_firstname = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_pass = new javax.swing.JPasswordField();
        txt_confpass = new javax.swing.JPasswordField();
        txt_nic = new javax.swing.JTextField();
        txt_contact = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_add1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_add2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Gender");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 90, -1));
        getContentPane().add(txt_add3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, 133, -1));

        btn_signup.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btn_signup.setText("Signup");
        btn_signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signupActionPerformed(evt);
            }
        });
        getContentPane().add(btn_signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 145, -1));

        rbtn_male.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rbtn_male.setText("Male");
        getContentPane().add(rbtn_male, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 132, -1));
        getContentPane().add(txt_lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 134, -1));

        rbtn_female.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rbtn_female.setText("Female");
        getContentPane().add(rbtn_female, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 150, -1));
        getContentPane().add(txt_firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 134, -1));
        getContentPane().add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 134, -1));
        getContentPane().add(txt_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 134, -1));
        getContentPane().add(txt_confpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, 133, -1));
        getContentPane().add(txt_nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 134, -1));
        getContentPane().add(txt_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 134, -1));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        jLabel1.setText("Create an Account");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 320, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("First name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 110, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Last name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 110, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 80, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 100, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Confirm Password");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 160, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("NIC");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 70, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Contact number");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 150, -1));
        getContentPane().add(txt_add1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 134, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Address");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 90, -1));
        getContentPane().add(txt_add2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, 119, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Standard-Room-1350x750-2.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static Connection con;
    
    private void btn_signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_signupActionPerformed
        
        try 
        {
            
            Statement st =  DBConnection.creatConnection().createStatement();
            
            String fname,lname,email,pw,confpw,nic,add1,add2,add3,gender, tele;
           
            fname = txt_firstname.getText();
            lname = txt_lastname.getText();
            email = txt_email.getText();
            pw = txt_pass.getText();
            confpw = txt_confpass.getText();
            nic = txt_nic.getText();
            add1 = txt_add1.getText();
            add2 = txt_add2.getText();
            add3 = txt_add3.getText();
            tele = txt_contact.getText();
            
            if(rbtn_male.isSelected()){
                gender = "male";
            }else{
                gender = "female";
            }
            
            String query = "INSERT INTO `guest_details` (`first_name`, `last_name`, `nic`, `address`,`address2`,`address3`, `gender`, `contact_no`, `email`, `password`) VALUES ('"+fname+"', '"+lname+"', '"+nic+"', '"+add1+"','"+add2+"','"+add3+"', '"+gender+"', '"+tele+"', '"+email+"', '"+pw+"');";
            
            
            System.out.println(query);
            
            int count = st.executeUpdate(query);
            if(count > 0){
                System.out.println("Ok");
            }
            
        } 
        catch (SQLException ex) 
        {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btn_signupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signupform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signupform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signupform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signupform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signupform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_signup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton rbtn_female;
    private javax.swing.JRadioButton rbtn_male;
    private javax.swing.JTextField txt_add1;
    private javax.swing.JTextField txt_add2;
    private javax.swing.JTextField txt_add3;
    private javax.swing.JPasswordField txt_confpass;
    private javax.swing.JTextField txt_contact;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_firstname;
    private javax.swing.JTextField txt_lastname;
    private javax.swing.JTextField txt_nic;
    private javax.swing.JPasswordField txt_pass;
    // End of variables declaration//GEN-END:variables
}
