/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Chamod
 */
public class UserManageform extends javax.swing.JFrame {

    /**
     * Creates new form UserManageform
     */
    public UserManageform() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_pass = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        txt_confpass = new javax.swing.JPasswordField();
        txt_add1 = new javax.swing.JTextField();
        txt_nic = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_contact = new javax.swing.JTextField();
        txt_add2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_add3 = new javax.swing.JTextField();
        btn_signup = new javax.swing.JButton();
        rbtn_male = new javax.swing.JRadioButton();
        txt_lastname = new javax.swing.JTextField();
        rbtn_female = new javax.swing.JRadioButton();
        txt_firstname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btn_signup1 = new javax.swing.JButton();
        btn_signup2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(txt_pass);
        txt_pass.setBounds(350, 200, 134, 22);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Contact number");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(166, 280, 140, 25);
        getContentPane().add(txt_confpass);
        txt_confpass.setBounds(700, 200, 133, 22);
        getContentPane().add(txt_add1);
        txt_add1.setBounds(350, 330, 134, 22);
        getContentPane().add(txt_nic);
        txt_nic.setBounds(350, 240, 134, 22);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Address");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(163, 320, 90, 25);
        getContentPane().add(txt_contact);
        txt_contact.setBounds(350, 280, 134, 22);
        getContentPane().add(txt_add2);
        txt_add2.setBounds(510, 330, 119, 22);

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Update information");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(300, 0, 340, 58);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("First name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(168, 80, 100, 25);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Last name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(167, 120, 100, 25);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Email");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(167, 160, 70, 25);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Password");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(162, 200, 100, 25);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Gender");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(168, 360, 80, 25);
        getContentPane().add(txt_add3);
        txt_add3.setBounds(640, 330, 133, 22);

        btn_signup.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_signup.setText("Update");
        btn_signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signupActionPerformed(evt);
            }
        });
        getContentPane().add(btn_signup);
        btn_signup.setBounds(200, 440, 145, 31);

        rbtn_male.setText("jRadioButton1");
        getContentPane().add(rbtn_male);
        rbtn_male.setBounds(350, 370, 98, 20);
        getContentPane().add(txt_lastname);
        txt_lastname.setBounds(350, 120, 134, 22);

        rbtn_female.setText("jRadioButton2");
        getContentPane().add(rbtn_female);
        rbtn_female.setBounds(510, 370, 98, 20);
        getContentPane().add(txt_firstname);
        txt_firstname.setBounds(350, 80, 134, 22);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Confirm Password");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(520, 200, 170, 25);
        getContentPane().add(txt_email);
        txt_email.setBounds(350, 160, 134, 22);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("NIC");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(164, 240, 60, 25);

        btn_signup1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_signup1.setText("Delete");
        btn_signup1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signup1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_signup1);
        btn_signup1.setBounds(420, 440, 145, 31);

        btn_signup2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_signup2.setText("Back");
        btn_signup2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signup2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_signup2);
        btn_signup2.setBounds(640, 440, 145, 31);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Standard-Room-1350x750-2.jpg"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(6, -1, 890, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_signupActionPerformed

       
    }//GEN-LAST:event_btn_signupActionPerformed

    private void btn_signup1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_signup1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_signup1ActionPerformed

    private void btn_signup2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_signup2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_signup2ActionPerformed

    public void setData(String user,String pass){
        DBConnection obj = new DBConnection();
        ResultSet rst =  obj.getUserInformation(user, pass);
        try {
            
            String fname = null,lname = null,nic = null,add = null,add2 = null,add3 = null,gender = null,tele = null,email = null,password = null;
            
            while(rst.next()){
                fname = rst.getNString("first_name");
                lname = rst.getNString("last_name");
                nic = rst.getNString("nic");
                add = rst.getNString("address");
                add2 = rst.getNString("address2");
                add3 = rst.getNString("address3");
                gender = rst.getNString("gender");
                tele = rst.getNString("contact_no");
                email = rst.getNString("email");
                password = rst.getNString("password");
                
                
            }
            txt_firstname.setText(fname);
            txt_lastname.setText(lname);
            txt_nic.setText(nic);
            txt_add1.setText(add);
            txt_add2.setText(add2);
            txt_add3.setText(add3);
            txt_contact.setText(tele);
            txt_email.setText(email);
            txt_pass.setText(password);
           
            if(gender.equalsIgnoreCase("male")){
                rbtn_male.setSelected(true);
            }else{
                rbtn_female.setSelected(true);
            }
            
        } catch (SQLException ex) { Logger.getLogger(UserManageform.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserManageform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserManageform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserManageform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserManageform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserManageform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_signup;
    private javax.swing.JButton btn_signup1;
    private javax.swing.JButton btn_signup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton rbtn_female;
    private javax.swing.JRadioButton rbtn_male;
    private javax.swing.JTextField txt_add1;
    private javax.swing.JTextField txt_add2;
    private javax.swing.JTextField txt_add3;
    private javax.swing.JPasswordField txt_confpass;
    private javax.swing.JTextField txt_contact;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_firstname;
    private javax.swing.JTextField txt_lastname;
    private javax.swing.JTextField txt_nic;
    private javax.swing.JPasswordField txt_pass;
    // End of variables declaration//GEN-END:variables
}
